### ISSUE TITLE
Easier Init

### ISSUE THREAD

**Issue by AmyMialee** [Bawnorton/MixinSquared#1]
It would be really nice if this could have an easier initializer similar to what mixinextras has on it's new beta releases (on fabric anyway).
https://gist.github.com/LlamaLad7/ec597b6d02d39b8a2e35559f9fcce42f

**Comment by Bawnorton** [comment]
Not sure what you mean as the only difference between initialising this and MixinExtras is MixinExtras is on Maven central

**Comment by AmyMialee** [comment]
On fabric you don't need to do a prelaunch init using their new system.

**Comment by AmyMialee** [comment]
nevermind I can't read lol
