### ISSUE TITLE
[Question] Can I remove a method, or its annotation?

### ISSUE THREAD

**Issue by SettingDust** [Bawnorton/MixinSquared#10]
I want to avoid a mixin method from applying

**Comment by Bawnorton** [comment]
Yes, the [Annotation Adjuster](https://github.com/Bawnorton/MixinSquared/wiki/Mixin-Annotation-Adjuster) can remove annotations on handlers before they are processed, effectively removing it's ability to be injected.

**Comment by SettingDust** [comment]
Oh. I missing that.
