### ISSUE TITLE
[Question] Is It Possible To Do This With An @Unique method?

### ISSUE THREAD

**Issue by LogicalMaximus** [Bawnorton/MixinSquared#16]

**Comment by Bawnorton** [comment]
Should work in theory, use the print argument in the target handler annotation to see the available targets

**Comment by LogicalMaximus** [comment]
I turned on print in the target handler but I can't seem to find the logs for it, so I was wondering where the logs print?

**Comment by Bawnorton** [comment]
Giant box printed to the error output. It'll be red if you have log syntax highlighting
