### ISSUE TITLE
Reference injected @Unique fields

### ISSUE THREAD

**Issue by MehVahdJukaar** [Bawnorton/MixinSquared#4]
Would it be possible to have a way to reference fields added by other mods mixins?

**Comment by Bawnorton** [comment]
You can shadow merged fields from other mixins provided your mixin applies later, but just to clarify, I assume you're referencing shadowing fields that have been mangled by `@Unique` when the field name and type conflict with a field already present in the class?

i.e. be able to reference the second `test`:
```java
    @Unique
    @MixinMerged(
        mixin = "com.bawnorton.sandbox.mixin.LivingEntityMixin",
        priority = 1000,
        sessionId = "59d35d25-9705-43e2-a28a-d0d369525b9c"
    )
    private String test = "Hello, world!";
    @Unique
    @MixinMerged(
        mixin = "com.bawnorton.sandbox.mixin.LivingEntityMixin2",
        priority = 1000,
        sessionId = "59d35d25-9705-43e2-a28a-d0d369525b9c"
    )
    private String fd525b9c$test$0 = "Hello world, the second time!";
```

**Comment by MehVahdJukaar** [comment]
I was referring to just referencing new fields added by other mixins that also have unique annotation. I didn't know you could already do that, tho in which case what value would the session id string need to be?

**Comment by Bawnorton** [comment]
The `sessionId` string is not deterministic. In fact, it's always `UUID.randomUUID().toString()`, the `mixin` value can annotated element are enough to identify specific targets

**Comment by Bawnorton** [comment]
Not Planned
